Aptukov_LAB_2_2
Nika-Keks/spbstu-algos-2-1 pull request #12
Opened 2022-10-30 12:24 UTC by LuckyAm20

2022-10-30 20:17 UTC, Nika-Keks requested changes

2022-10-30 20:17 UTC, Nika-Keks commented on laba_2/function.c
> +    (list*)(user_element->next) = ptr;
А как работает вот эта строка (59)?

2022-10-30 20:17 UTC, Nika-Keks commented on laba_2/main.c
> +        push(test,i,size);
push у Вас принимает list** а Вы передаете list*
Программа не собирается

2022-10-30 20:24 UTC, Nika-Keks commented
@LuckyAm20 

1. Программа не собирается и это надо исправить
2. Суть задания - написать 2 процедуры (m_alloc, m_free) и в main должна быть продемонстрирована именно их работа, список в этой лабе служит лишь вспомогательным инструментом
3. Комментарии не читаются на github, их нужно либо написать на английском, либо сохранить файлы в юникоде

p.s. соберите, пожалуста, все файлы по первой лабе в одну директорию

2022-10-31 16:25 UTC, LuckyAm20 commented on laba_2/function.c
> +    (list*)(user_element->next) = ptr;
Эта функция добавляет элемент в список свободного пространства, а сама строка присваивает параметру next начальный адрес свободного блока памяти.

2022-10-31 17:31 UTC, LuckyAm20 commented
Исправил ошибки, в visual studio программа собирается. Для файлов main.c и function.h исправил комментарии, комментарии в файле function.c отображаются на русском в github. Я использовал список, как вспомогательный элемент, для хранения начальных адресов выделенной пользователям памяти(блоков). Для примера представлено выделение памяти для списка. Файлы для первой лабораторной работы объединил.

2022-11-01 11:34 UTC, Nika-Keks commented on laba_2/main.c
> +        push(test,i,size);
Вы исправили ошибку совершенно не тем образом, теперь несоответствий типов стало только больше

2022-11-01 11:38 UTC, Nika-Keks commented
@LuckyAm20 исправьте ошибку в 59 строке и почините несоответствия типов
Советую включить все предупреждения и обращать на них внимание

2022-11-01 15:43 UTC, LuckyAm20 commented on laba_2/main.c
> +        push(test,i,size);
передаю теперь list** в push

2022-11-07 18:30 UTC, Nika-Keks commented
@LuckyAm20 лаба 2 - хорошо, лаба 3 - отлично, обе работы зачтены, жду следующую

2022-11-07 18:30 UTC, merged