Add lab2
Nika-Keks/spbstu-algos-2-1 pull request #15
Opened 2022-11-01 22:37 UTC by vladimir-skvortsov

@Nika-Keks Здравствуйте, не совсем понял шестое задание второй лабораторной. Где необходимо использовать списки? Нужно разбивать не помещающиеся никуда процессы на несколько связанных блоков и «распихивать» их по разным блокам памяти?

2022-11-02 07:49 UTC, Nika-Keks commented
@vladimir-skvortsov 
1. В лабе необходимо написать 2 процедуры (m_alloc, m_free)
Суть в следующем, у Вас есть кусок памяти (его можно выделить как угодно), этот кусок изначально считается свободным
Далее пользователь Ваших m_alloc и m_free вызывает первую функцию и получает указатель на из диапазона выделенного куска
Чтобы потом m_free смог правильно вернуть этот кусок, информация о выделенном куске должна сохраниться в списке (глобальная переменная или, я бы предпочел, передать в m_alloc и m_free в виде дескриптора 
2. Написать процедуру проверки целостности
Для этого нужно проверить валидность адресов занятой памяти (в списке) и их офсетов

2022-11-05 14:03 UTC, vladimir-skvortsov commented
@Nika-Keks вроде исправил. Я забыл и случайно закоммитил наработке по 6 лабе, потом открою отдельный пр, как деделаю

2022-11-07 18:42 UTC, Nika-Keks requested changes
Программа не собирается из-за неопределенных функций
Проверьте, что все хедеры стандартных библиотек подлючены везде где это необходимо

2022-11-07 18:42 UTC, Nika-Keks commented on lab2_task6/main.c
> +#include "utils.c"
Так делать не стоит
Это нужно исправить

2022-11-08 08:48 UTC, vladimir-skvortsov commented on lab2_task6/main.c
> +#include "utils.c"
@Nika-Keks исправил

2022-11-12 14:07 UTC, Nika-Keks commented
@vladimir-skvortsov отлично, зачтено

2022-11-12 14:07 UTC, merged