lab1_ex2_Tabakova
Nika-Keks/spbstu-algos-2-1 pull request #27
Opened 2022-11-13 15:54 UTC by VictoriaTabakova

2022-11-15 22:42 UTC, Nika-Keks requested changes
@VictoriaTabakova 
Нашел есдинственное замечание, его надо исправить
В остальном все отлично

2022-11-15 22:42 UTC, Nika-Keks commented on lab1/main.c
> +#include "list.c"
Из-за этой строки программа не собирается, причина: пножественное определение
Инклюдать си файлы не самая лучшая практика

2022-11-16 14:17 UTC, VictoriaTabakova commented on lab1/main.c
> +#include "list.c"
@Nika-Keks добавила .h файлы

2022-11-22 09:27 UTC, Nika-Keks requested changes

2022-11-22 09:27 UTC, Nika-Keks commented on lab_3_ex_4/poly.c
> +  polynom->numbers = malloc(0);
malloc(0) - это что-то странное, это дает runtime error, программа падает сразу после запуска

2022-11-22 09:30 UTC, Nika-Keks commented
@VictoriaTabakova 
Первая лаба зачтена, отлично
А третья лаба падает, её надо поправить
Лучше просто поменять malloc(0) на NULL

2022-11-24 22:47 UTC, VictoriaTabakova commented on lab_3_ex_4/poly.c
> +  polynom->numbers = malloc(0);
@Nika-Keks исправила, заменила malloc(0) на malloc(sizeof(int)), а не на NULL, потому что позже используется realloc

2022-11-25 20:04 UTC, VictoriaTabakova commented
@Nika-Keks, добавила лабораторную работу №4

2022-11-27 18:15 UTC, VictoriaTabakova commented
@Nika-Keks, отправила лабораторную №5

2022-11-28 14:59 UTC, VictoriaTabakova commented
@Nika-Keks, добавила лабораторную №6

2022-11-28 18:24 UTC, Nika-Keks reviewed
Третья лаба падает с "malloc(): invalid size"
К 4, 5, 6 написал замечания

2022-11-28 18:24 UTC, Nika-Keks commented on lab_4_ex_3/list.c
> +
Тут должен быть #include "list.h"
Иначе тип Node не определен

2022-11-28 18:24 UTC, Nika-Keks commented on lab_5_ex_15/main.c
> +#include "tree.c"
Это multiple definition

2022-11-28 18:24 UTC, Nika-Keks commented on lab_6_ex_10/main.c
> +#include "tree.c"
Это тоже multiple definition

2022-12-05 13:36 UTC, VictoriaTabakova commented
@Nika-Keks, исправила ошибки

2022-12-05 13:39 UTC, VictoriaTabakova commented
@Nika-Keks, в третьей работе не смогла воспроизвести ошибку

2022-12-06 18:59 UTC, Nika-Keks commented
@VictoriaTabakova 
Лабы 3, 4, 5 зачтены, хорошо
Лабу 6 надо поправить

2022-12-09 17:52 UTC, VictoriaTabakova commented
@Nika-Keks, подправила лабу 6

2022-12-13 09:25 UTC, Nika-Keks commented
@VictoriaTabakova 
Работа зачтена
Поздравляю

2022-12-13 09:25 UTC, merged