lab1_3 babahina Sofya
Nika-Keks/spbstu-algos-2-1 pull request #28
Opened 2022-11-13 18:30 UTC by baru1ina

2022-11-15 23:10 UTC, Nika-Keks requested changes
@baru1ina 
Основная проблема - программа падает при запуске с сегфолдом
В остальном все выглядит неполохо

2022-11-15 23:10 UTC, Nika-Keks commented on 1_3/main.c
> +typedef struct {
А зачем Вам объявления этих структу рв си файле, если Вы уже все объявили в хедере?

2022-11-15 23:10 UTC, Nika-Keks commented on 1_3/main.c
> +} List;
В строке 23 типа struct List ещё не существует, он появится только на 24ой строке

2022-11-15 23:10 UTC, Nika-Keks commented on 1_3/main.c
> +		fscanf_s(file, "%i %i %i", &date->day, &date->month, &date->year);
Используйте, пожалуйста, обычный fscanf

2022-11-22 09:38 UTC, Nika-Keks requested changes
@baru1ina 
Если убрать касты все работает и лаба зачтена, но они есть
Уберите их и будем считать что договорились

2022-11-22 09:38 UTC, Nika-Keks commented on 1_3/main.c
> +		(List*)new->next = (List*)*inp;
Тут все было хорошо, зачем Вы добавили эти касты?
Каст справа от оператора = это ошибка, такое не компилируется

2022-11-22 11:06 UTC, baru1ina commented on 1_3/main.c
> +		(List*)new->next = (List*)*inp;
Исправила

2022-11-22 11:28 UTC, Nika-Keks commented
@baru1ina 
Не исправили в main.c:62

Предупреждения летят из-зи определения типа List
Вот Ваше определение
```
typedef struct List {
	Profile* profile;
	Date* date;
	struct List* next;
} List;
```

А вот каким его стоило сделать

```
typedef struct List_t { // имя в этой строке ...
	Profile* profile;
	Date* date;
	struct List_t* next; // и в этой строке ...
} List; // должны отличаться от имени в этой строке
```

2022-11-22 11:29 UTC, Nika-Keks commented
Лаба зачтена, отлично

2022-11-22 11:30 UTC, merged