Lab1_2_Afanasyev_Andrew
Nika-Keks/spbstu-algos-2-1 pull request #3
Opened 2022-09-28 13:49 UTC by afafos

2022-10-03 18:43 UTC, Nika-Keks requested changes

2022-10-03 18:43 UTC, Nika-Keks commented on algorithm.c
> +#include "./structure.c"
Инклюдать сишник не самая хорошая затея, обычно включают файлы .h
Вопрос Вам: Почему? Чем это может грозить?

2022-10-03 18:43 UTC, Nika-Keks commented on algorithm.c
> +Array_Data_Creation(int lines_count, char** array);
Небольшое замечание на будущее, сейчас можно не исправлять
Посмотрите что такое camelcase и snakecase

2022-10-03 18:43 UTC, Nika-Keks commented on algorithm.c
> +		for (j = 0; j < 40; j++)
Комментарий:
На такие случаи есть функция memcpy

2022-10-03 18:43 UTC, Nika-Keks commented on algorithm.c
> +Array_Words_Creation(char** array, int lines_count, char** arr_words);
И где же все возвращаемые значения?
Программа не собирается

2022-10-03 18:56 UTC, Nika-Keks commented
@afafos работа не собирается, это основное замечание, исправьте, остально проверю после этого

2022-10-04 15:59 UTC, afafos commented on algorithm.c
> +#include "./structure.c"
Возможно, из-за того, что может случиться множественное определение одних и тех же функций (при включении .с файлов).

2022-10-09 16:38 UTC, Nika-Keks commented
@afafos в лабе Вы активно используете массивы, этого быть не должно
Предполагается, что Вы будуте построчно считывать файл, распаршивать каждую строку на (слово, число) и сразу добавлять эту пару в список так чтобы он оставался отсортированным
Массивы сортировать не нужно
Плюс у Вас есть утечки памяти и ошибочные неявные касты, компилируйте программу с нужными флагами и не игнорируйте предупреждения

2022-10-11 18:49 UTC, afafos commented
Исправил, теперь без массивов.

2022-10-13 18:52 UTC, Nika-Keks commented
@afafos уже лучше, только переместите все файлы в директорию lab-1, чтобы лабы были отделимы друг от друга, и можно считать что мы договорились

2022-10-13 19:15 UTC, afafos commented
Сделал: поместил все файлы в папку lab_1.

2022-10-15 09:48 UTC, Nika-Keks commented
@afafos хорошо, лаба зачтена, жду следующую работу

2022-10-15 09:48 UTC, merged