laba_3.5
Nika-Keks/spbstu-algos-2-1 pull request #55
Opened 2022-11-29 13:08 UTC by pshenix

2022-12-06 19:48 UTC, Nika-Keks requested changes

2022-12-06 19:48 UTC, Nika-Keks commented on matrix.c
> +	list** arr_2 = Fill("matrix_2.txt", &weidht_2, &height_2);
Эти файлы тоже должны быть в репозитории

2022-12-06 19:50 UTC, Nika-Keks commented
@pshenix 
Работа написана неплохо, а вот оформление репозитория хромает
Посмотрите, пожалуйста, как структурировали репы Ваши коллеги
Ну и недостающие файлы надо добавить и работа будет зачтена

2022-12-13 09:39 UTC, Nika-Keks commented
@pshenix 
Лабы 3, 4 зачтены, отлично

2022-12-13 09:40 UTC, merged

2022-12-22 00:47 UTC, pshenix commented
Доброе утро!
Столкнулась с проблемой, что теперь вовсе не создается новый пулл реквест,
поэтому пока скину через почту лабы, но постараюсь решить проблему выше.
tree.c & tree.txt - 5.2
bin_tree.c - 6.9

#include <stdlib.h>
#include <malloc.h>
#include <stdio.h>
#pragma warning(disable:4996)

typedef struct tree {
	int value, num;
	struct tree* left;
	struct tree* right;
}tree;

int** Fill(char const* filename) {
	FILE* f = fopen(filename, "r");
	int n; // value of nodes
	int num_kid, kid; // count of descendants and kids also 
	fscanf(f, "%d", &n);
	int** nodes = (int**)malloc(sizeof(int*) * n);
	for (int i = 0; i < n; i++) {
		fscanf(f, "%d", &num_kid);
		nodes[i] = (int)malloc(sizeof(int) * num_kid);
		for(int j = 0; j < num_kid; j++){
			fscanf(f, "%d", &kid);
			nodes[i][j] = kid;
		}
	}
	fclose(f);
	return nodes;
}

tree* BuildingTree(tree* t, int** nodes, int num_node) {
	if(sizeof(nodes[num_node]) / sizeof(int*) == 1){
		t->left = BuildingTree(t, nodes, nodes[num_node][0]);
		t->right = NULL;
	}
	if (sizeof(nodes[num_node]) / sizeof(int*) == 2) {
		t->left = BuildingTree(t, nodes, nodes[num_node][0]);
		t->right = BuildingTree(t, nodes, nodes[num_node][1]);
	}
	if (sizeof(nodes[num_node]) == 0) {
		t->right = NULL; t->left = NULL;
	}
	return t;
}

int tree_petals(tree* t) {
	if (t->left != NULL) { t->value += tree_petals(t->left); }
	if (t->right != NULL) { t->value += tree_petals(t->right); }
	if (t->left == NULL && t->right == NULL) { return 1; }
	if (t->num == 0) { return 0; }
	else { return t->value; }
}

void TreePrint(tree* t, int level) {
	if (t) {
		TreePrint(t->left, level + 1);
		for (int i = 0; i < level; i++) { printf(" "); }
		printf("%d\n", t->value);
		TreePrint(t->right, level + 1);
	}
}

int main() {
	char const* filename = "tree.txt";
	int** nodes = Fill(filename);
	tree* t = malloc(sizeof(tree)); 
	t->value = 0; 
	t->num = 0; 
	t->left = NULL; 
	t->right = NULL;
	t = BuildingTree(t, nodes, 0);
	tree_petals(t);
	TreePrint(t, 0);
	return 0;
}
6
2 2 3
2 4 5
1 6
0
0
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include <locale.h>
#include <stdio.h>
#pragma warning(disable:4996)

typedef struct tree {
	int num, key;
	struct tree* left, * right;
} tree;

void TreePrint(tree* t, int lvl) {
	if (t) {
		TreePrint(t->left, lvl + 1);
		for (int i = 0; i < lvl; i++) { printf("      "); }
		printf("%d", t->key);
		TreePrint(t->right, lvl + 1);
		printf("\n");
	}
}

int Counting(tree* t) {
	if (t->left != NULL) { t->num += Counting(t->left); }
	if (t->right != NULL) { t->num += Counting(t->right); }
	if (t->left == NULL && t->right == NULL) { return 1; }
	return t->num;
}

void Search_k(tree* t, int k, int* flag) {
	int r;
	if (t->left) { r = t->left->num + 1; }
	else { r = 1; }
	if (r != k) {
		if (k < r) { Search_k(t->left, k, flag); }
		else { Search_k(t->right, k - r, flag); }
	}
	else {
		if (t->key % 2 == 0) { *flag = 1; }
		printf("k min element %d\n", t->key);
	}
}

void SmallerElemThanK(tree* t, int k, int elem) {
	int min = 1 + elem;
	if (t->left) {
		SmallerElemThanK(t->left, k, 0);
		min += t->left->num;
	}
	if (min <= k) {
		printf("\n%d min elem: %d\n", min, t->key);
		if (t->right) { SmallerElemThanK(t->right, k, min); }
	}
}

tree* newNode(int node_key) {
	tree* node; node = malloc(sizeof(tree));
	node->key = node_key;
	node->num = 1;
	node->left = NULL; node->right = NULL;
	return node;
}

tree* add(tree* t, int node_key) {
	if (!t) { return newNode(node_key); }
	if (node_key < t->key) { t->left = add(t->left, node_key); }
	if (node_key > t->key) { t->right = add(t->right, node_key); }
	return t;
}

int main() {
	tree* t = NULL; // create tree
	int n, node_key, k;
	printf("Write count of tree's nodes: ");
	scanf("%d", &n);
	for (int i = 0; i < n; i++) {
		printf("\nEnter %d value of node: ", i + 1);
		scanf("%d", &node_key);
		t = add(t, node_key);
	}
	// found value of number in each node
	Counting(t);
	// create flag and call function to find k-th min elem
	// if min elem % 2 == 0 -> flag = 1 else flag = 0
	int flag = 0;
	printf("\nWrite value of k: ");
	scanf("%d", &k);
	Search_k(t, k, &flag);
	if (flag == 1) {
		SmallerElemThanK(t, k, 0);
	}
	printf("\nFinal tree: \n");
	TreePrint(t, 0);
	return 0;
}