Горюнов Максим
Nika-Keks/spbstu-algos-2-1 pull request #61
Opened 2022-12-06 20:26 UTC by MaxGoryunov

Лабораторные по вариантам: 
1 - 6
3 - 14
4 - 13
5 - 15
6 - 15

2022-12-13 09:58 UTC, Nika-Keks requested changes

2022-12-13 09:58 UTC, Nika-Keks commented on Lab3_6/Lab3_6/treemain.c
> +	time_t t;
А откуда берется этот тип (time_t)?

2022-12-13 10:00 UTC, Nika-Keks commented
@MaxGoryunov 
Работы 1, 4, 5 зачтены, отлично
Работа 3 падает с сегфолдом
Работу 6 надо немного поправить

2022-12-13 16:55 UTC, MaxGoryunov commented on Lab3_6/Lab3_6/treemain.c
> +	time_t t;
Я добавил еще один коммит по 6-й лабораторной. time_t t и функция time() относятся к файлу time.h, который нужен для задания начального положения генератора чисел в rand().

2022-12-13 16:55 UTC, MaxGoryunov commented
В 3-ю лабораторную добавил файл с условиями узлов conds.txt. Теперь должно собраться.

2022-12-22 10:50 UTC, Nika-Keks commented
@MaxGoryunov 
Хорошо, зачтено

2022-12-22 10:50 UTC, merged