Add lab4
Nika-Keks/spbstu-algos-2-1 pull request #8
Opened 2022-10-16 15:05 UTC by vladimir-skvortsov

2022-10-16 18:50 UTC, Nika-Keks commented
@vladimir-skvortsov  сам алгоритм работает верно, но 
  - огромное количество утечек памяти 
  - комментарие есть, но их маловато
  - большое количество переходов от строки к инту и обратно, можно было сделать и без этого
  - передайте, пожалуйста, своим коллегам: инклюдать сишники НЕ надо, в Вашей группе это распространенная проблема
  
  Лабу я зачту т.к. суть предмета отражена верно, только уберите включение fs.c и почему Вы пропустили 2ую и 3ю работы?

2022-10-17 10:40 UTC, Nika-Keks requested changes

2022-10-21 07:04 UTC, vladimir-skvortsov commented on lab4_task1/main.c
> +  double total,
Как я понял, target чиатеся из файла и должен быть целым числом, а результат выражения может быть дробным (например 3+5/2)

2022-10-21 07:07 UTC, vladimir-skvortsov commented on lab4_task1/main.c
> +  int index,
Индекс цифры в числе для составления nextNumber и проверки, что число "закончилось" в начале функции backtrack

2022-10-21 07:40 UTC, vladimir-skvortsov commented on lab4_task1/main.c
> +#include "./fs.c"
Исправил

2022-10-21 07:46 UTC, vladimir-skvortsov commented on lab4_task1/main.c
> +      ? concat(concat(expression, "+"), intToString(nextNumber))
concat возвращает новую строку, так как она всегда разная. expression можно освободить только в самом конце функции backtrack, так как до этого эта переменная используется, разве нет?

2022-10-26 21:05 UTC, Nika-Keks commented
@vladimir-skvortsov , хорошо, работа зачтена, жду следующую

2022-10-26 21:05 UTC, merged