Романчук Евгений 5030102/10002 Лаба №1
Nika-Keks/spbstu-algos-2-1 pull request #9
Opened 2022-10-18 14:48 UTC by UUyy-Geniy

В первом комите лишние файлы, но как его удалить пока не разобрался.
Все необходимое во втором комите есть ("Romanchuk_Lab1_Var9_try2")

2022-10-26 21:24 UTC, Nika-Keks requested changes

2022-10-26 21:24 UTC, Nika-Keks commented on List/List/List.h
> +FILE* OpenFile(char* name, char* mode);//�������� ����� ��� ������ � ���
Не используйте кодировку win-1251, хотя это не влияет на работу программы, проверку это затрудняет
Самы простой вариант избежать проблемы с кодировками - не использовать русский алфавит
Лучше писать все на английском

2022-10-26 21:24 UTC, Nika-Keks commented on List/List/main.c
> +	int cnt = KolvoStrok(head);
Этой функции нет в хедере, из-за неё программа не собирается

2022-10-26 21:24 UTC, Nika-Keks commented
@UUyy-Geniy  неплохая работа, поправьте замечание с хедером и лаба зачтена

2022-10-26 21:31 UTC, Nika-Keks commented
И ещё упакуте все файлы по первой лабе в отдельную директорию, чтобы работы были отделимы
Ну и конечно мёжить нужно не main а в ветку со своим именем

2022-10-27 17:49 UTC, UUyy-Geniy commented
Хорошо, спасибо
В ближайшее время переделаю

чт, 27 окт. 2022 г. в 00:31, Аникин Александр ***@***.***>:

> И ещё упакуте все файлы по первой лабе в отдельную директорию, чтобы
> работы были отделимы
> Ну и конечно мёжить нужно не main а в ветку со своим именем
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Nika-Keks/spbstu-algos-2-1/pull/9#issuecomment-1292674887>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3DTOTRPKAAXPVRLZ62CZILWFGPLHANCNFSM6AAAAAARIFPNQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-30 09:35 UTC, Nika-Keks commented
@UUyy-Geniy, лаба зачтена, хорошо, жду следующую работу

2022-10-30 09:35 UTC, merged